name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: '3.x'
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Go module
      run: |
        cd dcsdog
        go mod download

    - name: Run tests
      run: |
        cd dcsdog
        task test

    - name: Build
      run: |
        cd dcsdog
        task build

    - name: Run linter
      run: |
        cd dcsdog
        task lint 