name: DcsDog CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: '1.24'
        cache: true

    - name: Install dependencies
      run: |
        cd dcsdog
        go mod download

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
        working-directory: dcsdog

    - name: Run go vet
      run: |
        cd dcsdog
        go vet ./...

    - name: Build
      run: |
        cd dcsdog
        go build -v ./...

    - name: Test
      run: |
        cd dcsdog
        go test -v ./... 